### ISSUE TITLE
fruit should allow to bind a class without a base

### ISSUE THREAD

**Issue by lutts** [google/fruit#10]
current implementation will give **SelfLoopError** with the following modified HelloWorld example

```
Component<GreeterImpl> getGreeterComponent() {
  return fruit::createComponent()
      .bind<StdoutWriter, StdoutWriter>()
      .bind<GreeterImpl, GreeterImpl>();
}
```

**Comment by poletti-marco** [comment]
Hi, what are you trying to do?

With that code, I think an error is expected behaviour (bind's purpose is
to bind a base class to a derived class). I suspect that you might achieve
what you want by simply removing the two bind calls altogether, since there
are no base-derived class relationships that you want Fruit to know about.
Does removing the two binds make your modified example code work as
expected? I'm not sure exactly what other changes you did to the example
code so it's hard for me to tell for sure.

The only possible improvement I can see here is having a more specific
error for this case, suggesting to remove the bind call altogether when the
base and derived types are the same.

**Comment by lutts** [comment]
Thank you. It works without the two binds. I think I must have a bind for every arguments of the constructor. Sorry to disturb you.

**Comment by poletti-marco** [comment]
I've now improved the error message for this case (in master, will be part of Fruit 1.1.0), to help other people in the same situation.
