### ISSUE TITLE
Difference with other C++ Dependency Injection libraries

### ISSUE THREAD

**Issue by qqibrow** [google/fruit#5]
Hi, I notice that there are another C++ DI libraries like [wallaroo](https://code.google.com/p/wallaroo/), and [Boost.DI](https://github.com/krzysztof-jusiak/di). What's the difference between fruit and them?  How this library been used in Google internally?

**Comment by poletti-marco** [comment]
I will include a page comparing Fruit to other C++ DI libraries in the Fruit website, thanks for the idea.
I'll work on the 1.1.0 release first though, once that is released I was already planning some work on the documentation (i.e., in 1 month or so).
I'll keep this issue open until I add that page, so that you know when it's there.

The TL;DR version is that Wallaroo is a completely different beast (run-time DI) while Boost.DI is more similar to Fruit, but there are some differences in the features (some are Fruit-only, some Boost.DI-only) and in performance (I expect Fruit to have noticeably faster compile time and slightly faster run-time, but I need to write some bench to have actual data on this).

**Comment by qqibrow** [comment]
Cool. That's very helpful. Thanks.

**Comment by icnocop** [comment]
Thank you for Fruit.

I'm also interested in a comparison with [hypodermic](https://github.com/ybainier/hypodermic).

**Comment by poletti-marco** [comment]
Hypodermic is also one of the runtime DI libraries, it's more similar to Wallaroo than to Fruit.
For example, if you forget to bind a type that's a compile-time error in Fruit (and Boost.DI) but it's a runtime error in Wallaroo and Hypodermic.

**Comment by soroshsabz** [comment]
ITNOA

@poletti-marco thanks for information, and what about [autowiring](https://github.com/leapmotion/autowiring)?

**Comment by poletti-marco** [comment]
Thanks for the pointer. It's the first time I hear about that.
I looked at the documentation but it's somewhat scarce, so it's hard for me
to compare I'm afraid.

**Comment by ruipacheco** [comment]
And what about Kangaru? Seems to be pretty complete: https://github.com/gracicot/kangaru/wiki

**Comment by poletti-marco** [comment]
From a quick look at the documentation it also seems to be runtime DI, so using an approach similar to Wallaroo and Hypodermic.
That means that it won't be able to report many compile-time errors that Fruit (and Boost.DI) can report, like missing bindings.

They provide a debugging facility for 1 class of errors:
https://github.com/gracicot/kangaru/wiki/11.-Debugging

But you need to modify your code in order to use it.
So I imagine that even for the few classes of errors where it does fail at compile-time, the errors are not very readable until you change your code to use that.

Fruit (and Boost.DI) give you the guarantee that certain classes of errors are always detected at compile-time, so if your code builds you're sure they won't happen at runtime. E.g. missing bindings (both libraries) or binding dependency cycles (Fruit only).
