### ISSUE TITLE
release plan

### ISSUE THREAD

**Issue by manuel-schiller** [google/fruit#52]
Hi Marco,

we plan on using fruit and were wondering when there will be a new release, as master is ahead 331 of the last release v2.0.4: https://github.com/google/fruit/compare/v2.0.4...master 

Thanks
Manuel

**Comment by poletti-marco** [comment]
You're right, it has been a while since the last release.
Don't worry, I'm planning to do a release soon (read: ~3 weeks).
I still want to implement #50 and possibly also #53 before I release 2.1.0 though.

If you can't wait that long, you can already start playing around with Fruit by building it at HEAD manually (https://github.com/google/fruit/wiki/install), it should be relatively stable at this point.
That said, you probably *should* wait for the proper 2.1.0 release before using it in a production system.

**Comment by poletti-marco** [comment]
I'm happy to announce that Fruit 3.0.0 has now been released, sorry for the wait and enjoy!
