### ISSUE TITLE
How to get singleton object

### ISSUE THREAD

**Issue by LinArcX** [google/fruit#76]
Hi. and thank you for this great repo.
I am developing a qt android application and in multiple files i want to access db object(exact same object) for db operations, imagin in classA, i init db object and call some functions on it.
```
    Injector<Repository> injector(getNutSqliteComponent);
    Repository* db(injector);
    std::cout << db->_id << std::endl;
    db->addToFavorites("foo", "bar");
```
In another file(classB), i want to get same db object. but it fails when i re-produce the code again:
```
    Injector<Repository> injector(getNutSqliteComponent);
    Repository* db(injector);
    std::cout << db->_id << std::endl;
    db->addToFavorites("zoo", "nar");
```
How to get singleton objects with fruit?
regards.

**Comment by poletti-marco** [comment]
Have you considered using the same injector?
The usual way to do DI is to have a single injector at toplevel (e.g. in main(), or in the setup method/function of a test) and then your classes should inject their dependencies instead of creating their own injectors.
Each class has 1 instance per injector, so if you share the injector it will become a singleton.

See the tutorial if you haven't seen it already, e.g. https://github.com/google/fruit/wiki/tutorial:-simple-system

You *can* have multiple injectors for more advanced use-cases (e.g. 1 created at startup and 1 created per request in a server, as in [this tutorial](https://github.com/google/fruit/wiki/tutorial:-server)).
However this is more complicated (since the two injectors will have different instances of classes), I would only do this if really necessary.
