### ISSUE TITLE
Using smart pointers to store references to dependencies in class

### ISSUE THREAD

**Issue by rgh2** [google/fruit#77]
I have a question concerning using smart pointers in the context of fruit.  In most of the examples given in the documentation the dependencies of a class are specified as class members of raw pointer type.  What if we wanted the dependencies expressed as class members that are of type std::shared_ptr or 
std::unique_ptr.  Is this possible in Fruit ?

**Comment by poletti-marco** [comment]
In Fruit the injector owns all injected objects.

For `std::shared_ptr` actually it's supported by Fruit (you can just inject `std::shared_ptr<T>` instead of `T*` if `T` is bound), however that objects *will* become invalid once the Injector is destroyed.

Injecting `std::unique_ptr<T>` is not supported when `T` is bound.
What is supported though is to bind/inject a `std::function<std::unique_ptr<T>()>` (also with some arguments if desired). Then you can get an instance by calling that function and it will be unique for each call, the injector does not own that object.
See https://github.com/google/fruit/wiki/quick-reference#factories-and-assisted-injection for more information on how to do this.

However then you have to be careful to not have e.g. references to injected classes within the class that you're creating. E.g. Fruit will let you inject a `Foo*` into your `T`, but if the injector is destroyed `Foo` will also be destroyed so if you're storing a `Foo*` as a field in `T` it will become invalid.

HTH, but if this is not clear or if you have further questions feel free to ask.
