### ISSUE TITLE
Cmake must be able to generate multiple configurations (Debug+Release+MinSizeRel)

### ISSUE THREAD

**Issue by matryoshkababushka** [google/fruit#81]
With Visual Studio 2017, it is common practice to switch between Debug and Release configurations. Dev builds are Debug builds and testing of programs is performed using nightly Release builds, released frequently.

<strike>VS [supports](https://stackoverflow.com/questions/7683869/what-does-the-link-library-dependency-linker-option-actually-do-in-visual-stud) option "Link library dependencies", e.g. marking one project in solution "dependent" from fruit will introduce auto linking</strike>. You now have to manually copy Release config to create Debug config and manually change settings to make a valid Debug configuration. After every change, you cannot re-generate with cmake otherwise you will have to do that again. 

I am posting this since i don't use Cmake normally myself and unable to resolve this myself. Is there a reason why `CMAKE_BUILD_TYPE` does not support `Debug;Release;MinSizeRel` value, but only single configurations, making it impossible to generate normal VS project?

I suggest fixing this if there is no problem with that.

**Comment by poletti-marco** [comment]
Hi, I'm not familiar with this "Link library dependencies" feature (I don't use Visual Studio myself, I just used it a bit to make sure Fruit works in VS too).
I tried to find some online guides explaining what to do, and looked around in VS itself, but I couldn't find it.
Could you please provide step-by-step instructions to reproduce what you're doing, so that I can then look into what can be done to fix it?

Fruit does some configuration checks (`CHECK_CXX_SOURCE_COMPILES`) that I expect will not "just work" with this multiple-configuration mode.
So I need to be able to reproduce what you're seeing to figure out which errors come up and how to fix them.

**Comment by poletti-marco** [comment]
No response after >1y, closing.
If this is still an issue, feel free to re-open, providing the information I mentioned above.
