### ISSUE TITLE
Add cmake config module

### ISSUE THREAD

**Issue by soroshsabz** [google/fruit#86]
ITNOA

Hi

I think it is good to provide cmake config module and targets because this module is very useful to make easier use of this library in another cmake base projects. also you have FindFruit module, but I think it is time that we use [moden cmake](https://cliutils.gitlab.io/modern-cmake/) and use modern native cmake features to generate these feature like many other google projects. :)

thanks

**Comment by soroshsabz** [comment]
related to #79

**Comment by poletti-marco** [comment]
It's not clear to me what advantages would Fruit users get with this.
Do you have something specific in mind? If so please explain so that I can
compare the priority of this vs other Fruit-related work.
(or even better, feel free to send a pull request)

I have some familiarity with the basics of cmake but I'm not an expert,
especially in more recent features / best practices.

**Comment by poletti-marco** [comment]
No answer after almost 1 year => closing.
Feel free to reopen if you have additional info.
