### ISSUE TITLE
shared_from_this() throws bad_weak_ptr exception when called from objects managed by fruit

### ISSUE THREAD

**Issue by Rwardc** [google/fruit#90]
gdb shows that the weak reference inside the shared_ptr is always empty. 

Is enable_shared_from_this<> supported for objects managed by the injectors?

**Comment by poletti-marco** [comment]
Looking at https://en.cppreference.com/w/cpp/memory/enable_shared_from_this, it seems that `shared_from_this` assumes that the pointer is owned by a `shared_ptr` which is not the case when using Fruit.

However, Fruit does allow you to inject a `shared_ptr` of the type, and I would recommend doing that rather than having the object itself expose a reference.
If this is not clear, please provide some simple code that shows your use case and I can explain how to migrate to injecting a `shared_ptr` in that case.

Note that even when injecting a `shared_ptr` the object is still owned by the injector so the `shared_ptr` will become invalid once the injector is deleted.

**Comment by Rwardc** [comment]
I believe I understand what you’re suggesting: using the same injector to get another reference to the same object, and passing that in place of shared_from_this(). I think this presents a problem though. How will the injector be passed into the object to be used for later method calls? Since it’s created and managed by the injector, the injector would need to inject itself into the constructor. Or am I understanding this incorrectly? As far as sample code goes, I’m not contriving anything complicated, I just want to use shared_from_this() from within an object returned from an injector. Nothing special. 

Also, I think this frameworks management of std::shared_ptrs is potentially dangerous, since it essentially violates the contract provided by a shared pointer: that the object referenced by the pointer will always be valid so long as the reference count is positive. From what I understand, it’s fully possible with fruit to delete the injector (maybe not intentionally) and all shared_ptr references to the objects managed by that injector become invalid. Is this correct?

**Comment by poletti-marco** [comment]
> I just want to use shared_from_this() from within an object returned from
an injector

As I mentioned this is not possible.

However I think that if you explain how you would use that shared pointer,
there should be an alternative way to do it, injecting the shared pointer
in the class that would *call* the method (not the one that would have the
method returning shared_from_this).

It's hard for me to help you without more info because you're describing
what you think is a possible solution (shared_from_this) instead of
describing the problem that you're trying to solve with it.
See https://en.wikipedia.org/wiki/XY_problem

**Comment by Rwardc** [comment]
Yes, sorry about that. I’m traveling right now and only have access to mobile, so it’s a bit difficult to post some example code. Let me try to explain the problem regardless:

Im working with a class ‘Server’ which uses a third party library to service connections. I did not write this class, but I am constrained with what I can modify. This third party library requires registering asynchronous callback methods to handle connection events. Currently this Server was calling shared_from_this() to pass a reference to itself to the third party library. There is a valid case in this particular implementation that the callback may hold the only reference to the Server object. In other words, it’s possible those callbacks may occur outside the scope of the injector’s lifetime.

**Comment by poletti-marco** [comment]
Can you keep the injector alive in some way?
E.g. if 1 injector for the Server class is enough in the whole process you
could have a static var that holds the injector, or hold it in a var in
main (or close enough) so that it remains alive.

With Fruit, injected objectd are always owned by the injector, and get
destroyed when the injector is.
If this is really not possible in this application then maybe Fruit is not
a good fit for this project.
You could inject a std::function and create objects using that, but at that
point I'm not sure if Fruit is more useful or just a complication.

Is this a large project that already uses Fruit?
Or a small project in which you're trying to switch to Fruit? In the former
case maybe it's worth going down the injected function route, in the 2nd
one I'd discourage this.

**Comment by poletti-marco** [comment]
Btw, not sure if you have many types like this where you have to pass a
shared pointer to a callback, but if it's just 1 at top level (Server) you
could create Server itself without using Fruit (e.g. using make_shared) and
have that create the injector for everything else, where the injector is
kept as a field of Server.

**Comment by Rwardc** [comment]
Thanks for your quick replies. 

I'm finally back at the office and I've taken a look at the fruit code. Looks like you are using the _aliasing constructor_ for the `std::shared_ptr` variant:
```
template <typename C>
struct GetSecondStage<std::shared_ptr<C>> {
  // This method is covered by tests, even though lcov doesn't detect that.
  std::shared_ptr<C> operator()(C* p) {
    return std::shared_ptr<C>(std::shared_ptr<char>(), p);
  }
};
```
Very clever, for sure. And I now understand the restrictions on `shared_from_this()`. Makes sense. However, I think I found an unrelated issue in your use of this constructor.

Here's the declaration of the aliasing constructor  in the STL:
```
template< class Y > 
shared_ptr( const shared_ptr<Y>& r, element_type* ptr ) noexcept;
```
And an explanation of its properties and associated contract:
> The aliasing constructor: constructs a shared_ptr which shares ownership information with the initial value of r, but holds an unrelated and unmanaged pointer ptr. If this shared_ptr is the last of the group to go out of scope, it will call the stored deleter for the object originally managed by r. **_However, calling get() on this shared_ptr will always return a copy of ptr. It is the responsibility of the programmer to make sure that this ptr remains valid as long as this shared_ptr exists_**, such as in the typical use cases where ptr is a member of the object managed by r or is an alias (e.g., downcast) of r.get()

As I said earlier:

> Also, I think this frameworks management of std::shared_ptrs is potentially dangerous, since it essentially violates the contract provided by a shared pointer: that the object referenced by the pointer will always be valid so long as the reference count is positive. From what I understand, it’s fully possible with fruit to delete the injector (maybe not intentionally) and all shared_ptr references to the objects managed by that injector become invalid.

This is the sort of thing that can really confuse people. When you use types with well-understood behavior, it should follow the expected behavior.

**Comment by Rwardc** [comment]
> Is this a large project that already uses Fruit?
Or a small project in which you're trying to switch to Fruit? 

Its a small project that's going to grow into a large one. I was hoping to integrate a DI framework to help with the growing pains later.

> You could inject a std::function and create objects using that, but at that
point I'm not sure if Fruit is more useful or just a complication.

I've got a few options to try. My hope is to keep the fruit specific code out of our business logic, and I've got some ideas about modifying the server code to make sure that happens.

**Comment by poletti-marco** [comment]
> This is the sort of thing that can really confuse people. When you use
types with well-understood behavior, it should follow the expected behavior.

I agree that this is somewhat problematic, let me give more context.
When I designed/implemented this part of Fruit I had 3 choices:

1) Don't allow injecting shared_ptr at all.

However some people might need to pass shaded_ptrs to some other code that
doesn't use Fruit (either in their own project if they're migrating, or
elsewhere).

2) Allocate all injected objects using shared_ptr

However this would introduce a significant hit in terms of performance and
also an increase in code size.
This would also affect users of Fruit that don't need shared_ptr at all.

3) Allow injecting shared_ptr but with an unusual contract: they're
invalidated on injector destruction.

This is what I went for, and I still think it's the best choice.
I tried documenting this limitation in various places to (try to) make sure
that Fruit users are aware of this. If there are some places where it's not
mentioned and you think it should be, please suggest and I can add an
explanation (or a link to the explanation) there.

This is not a bug, when the shared_ptr documentation says that the pointer
must remain valid for the shared_ptr to be valid, Fruit passes on this
limitation to its users (with s/the pointer/the injector/).

**Comment by Rwardc** [comment]
Understood. I do appreciate the awesome work you've done with this library. 

> If there are some places where it's not
mentioned and you think it should be, please suggest and I can add an
explanation (or a link to the explanation) there.

I would suggest adding to the documentation that the `shared_ptr` returned by the library uses the alias constructor. Its an extra bit of detail that will clarify that certain features of the `shared_ptr` aren't available to objects managed by fruit. I'll close this issue now.

On an unrelated note, I've been trying to construct an injector that provides multiple types, as in your examples, but can't seem to get it to work. The compiler complains that there's no matching function call in Injector. Here's some contrived test code that has the problem:
```
class Context {
public:
    Context() : m(count++){}
    void print() {
        std::cout << "My count: " << m << "\n";
    }
private:
    static int count;
    int m;
};

int Context::count = 0;

class IBaseServer {
public:
    virtual void listen() = 0;
};

class IHttpServer : public IBaseServer {

};

class ITcpServer : public IBaseServer {

};

class TcpServer : public ITcpServer {
public:
    TcpServer(std::shared_ptr<Context> context) : mContext(std::move(context)) {}
    void listen() override {
        mContext->print();
    }
private:
    std::shared_ptr<Context> mContext;
};

class HttpServer : public IHttpServer {
public:
    HttpServer(std::shared_ptr<Context> context) : mContext(std::move(context)) {}
    void listen() override {
        mContext->print();
    }
private:
    std::shared_ptr<Context> mContext;
};
fruit::Component<Context> getContextComponent() {
    return fruit::createComponent()
    .registerConstructor<Context()>();
}

fruit::Component<fruit::Required<Context>, IHttpServer> getHttpServerComponent(){
    return fruit::createComponent()
    .registerConstructor<HttpServer(std::shared_ptr<Context>)>()
    .bind<IHttpServer,HttpServer>();
}
fruit::Component<fruit::Required<Context>, ITcpServer> getTcpServerComponent(){
    return fruit::createComponent()
    .registerConstructor<TcpServer(std::shared_ptr<Context>)>()
    .bind<ITcpServer,TcpServer>();
}

fruit::Component<ITcpServer, IHttpServer> getServersComponent(){
    return fruit::createComponent()
    .install(getHttpServerComponent)
    .install(getTcpServerComponent)
    .install(getContextComponent);
}

int main(int argc, char* argv[])
{

//    Injector<IHttpServer, ITcpServer> hs(getHttpServerComponent, getTcpServerComponent, getContextComponent); // <-- No matching function call found
    Injector<IHttpServer, ITcpServer> hs(getServersComponent); // <-- Same here
    auto httpServer = hs.get<std::shared_ptr<IHttpServer>>();
    auto tcpServer = hs.get<std::shared_ptr<ITcpServer>>();

    httpServer->listen();
    tcpServer->listen();


    return 0;
}
```
Did I completely misinterpret the documentation? My goal is to shared the `Context` object among all types returned by the injector. If that's not possible, then I'll try something else.
