### ISSUE TITLE
Premake support

### ISSUE THREAD

**Issue by Hampfh** [google/fruit#94]
Does fruit have support for **premake** builds? If not, how do I manually attach it to my project and exclude the boost dependency?

**Comment by poletti-marco** [comment]
No (not ATM at least).
Does CMake not work for you?
What kind of project are you talking about? (VS? XCode? CLion? ...)
There's a configuration knob to not use boost if you don't want it and are ok with the performance hit of using the stl instead.
See https://github.com/google/fruit/wiki/install.

**Comment by Hampfh** [comment]
I run the project in VS2019, I prefer to use premake as it's a framework I'm more knowledged about, I did however try to build fruit myself by creating the necessary premake files but ran into issues with premake not finding the file `fruit-config-base.h`. 

On another note, how large will the performance hit be if I decide to not use boost?

**Comment by poletti-marco** [comment]
Fruit has a non-trivial amount of logic in cmake to detect properties of the compiler/system and generate the correct config header and compile options.

If you want to rewrite that logic in fastbuild it's not going to be easy and it's not sth I'm planning to support given the low demand (it's the first time I hear about it) and the maintenance cost (if I make changes to fruit then I would not know how to update the config, since it's in lua).

Have you considered using cmake just for fruit (compiling it as a separate vs project) and then importing the built artifacts in your fastbuild project?

**Comment by Hampfh** [comment]
Okay, I see. I'll do as you suggest and do it in two steps then. Thanks
